In [1]:
import numpy as np

In [10]:
a = np.arange(6) + np.arange(0, 51, 10).reshape(6, 1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [16]:
# Diag starting at a[0,1] to a[4,5]
a[list(range(5)), list(range(1, 6))]

array([ 1, 12, 23, 34, 45])

In [14]:
# Same as before using np.diag
np.diag(a, k=1)

array([ 1, 12, 23, 34, 45])

In [17]:
# Extract some sub-columns
a[3:, [0, 2, 5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [20]:
# Extract sparse sub-column
mask = np.array([1, 0, 1, 0, 0, 1], dtype=bool)
a[mask, 2]

array([ 2, 22, 52])

In [21]:
# Set parts to 0
a[:,0] = 0
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 0, 11, 12, 13, 14, 15],
       [ 0, 21, 22, 23, 24, 25],
       [ 0, 31, 32, 33, 34, 35],
       [ 0, 41, 42, 43, 44, 45],
       [ 0, 51, 52, 53, 54, 55]])