In [1]:
import numpy as np

In [6]:
a = np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]
print(a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [5]:
# 3rd column
a[:,2][:, np.newaxis]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

In [10]:
# 1st line with col 4 & 5
a[0,3:5]

array([3, 4])

In [11]:
# Submatrix with a(2,0), a(2,2), a(2,4), a(4,0), a(4, 2), a(4,4)
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])